import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <div className="fixed inset-0 bg-bgPrimary"> </div>
        <div className="relative z-10 max-w-screen-2xl mx-auto h-dvh text-white flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
